services:
    app:
        build: .
        ports:
            - "3000:3000"
            - "5000:5000"
        depends_on:
            - mongodb
        volumes:
            - .:/webmessenger

    mongodb:
        image: mongo:5.0
        ports:
            - "27017:27017"
        volumes:
            - ./mongo_data:/data/db

volumes:
    mongo_data:
